### ISSUE TITLE
Banking apps refuse to work with accessibility settings enabled for gestures

### ISSUE THREAD

**Issue by szszoke** [MM2-0/Kvaesitso#1567]
Hello,

I tried to use this launcher and I enabled the accessibility settings to make gestures work.

The banking app in question specifically names this launcher as the reason why it refuses to work.

The gestures in question are:
- swipe down to open notification drawer
- swipe up to search

I am using Multi-Launcher for now and the gestures seem to work there without the need for accessibility settings.

Maybe it would be worth it to find out how it is done: https://github.com/DroidWorksStudio/mLauncher

**Comment by cr1za** [comment]
I just tried this Multi-Launcher and it definitely needs Accessibility settings on for the gestures to work, so you may have missed something.

**Comment by szszoke** [comment]
Interesting. I double checked and I don't have the accessibility settings enabled.

Which gestures did you try?

Double tap to lock the screen needs accessibility settings, but swipe down to open notifications doesn't.

**Comment by cr1za** [comment]
Ok, that's like the only one, all others need the accessibility.

**Comment by szszoke** [comment]
That, and swiping up for the app list, which for this launcher would be swiping up for search I guess.

**Comment by returntrip** [comment]
For me the problem is with any (banking) app that use  [BankID](https://play.google.com/store/apps/details?id=com.bankid.bus), they refuses to work when accessibility is enabled for Kvaesitso. 

"Error

To protect you from fraud, you can't use the BankID app while the Kvaesitso service is enabled. Disable Kvaesitso to proceed"

Cannot send the screenshot as BankID does not allow screenshots to be taken. 

I have tested with LawnChair and Nova Launcher the first has the same [problem](https://github.com/LawnchairLauncher/lawnchair/issues/5520) whilst Nova works fine.

**Comment by diogotcorreia** [comment]
Relevant code in mLauncher:
https://github.com/DroidWorksStudio/mLauncher/blob/bf8be4a01c1747c5037098790e1bd02a98a53bdc/app/src/main/java/com/github/droidworksstudio/mlauncher/ui/HomeFragment.kt#L572-L583

**Comment by returntrip** [comment]
I am now using a Samsung S25+ and this issue is not occuring on this device.

**Comment by returntrip** [comment]
The issue has returned after updating to v 1.38.

**Comment by WilliamKimball0** [comment]
Most launchers (Lawnchair, nova..) have working swipe for notifications without accessibility service needing to be enabled. This requirement from banking apps is huge issue and getting worse by the minute, hope this can be fixed.

**Comment by MM2-0** [comment]
Fixed in #1784

**Comment by WilliamKimball0** [comment]
I'm running latest version of Kvaesitso (1.39.3) and when I enable the "Open notification drawer" gesture I still get the Accessibility service permission ask. The funny thing is that doing the gesture reveals this lock icon from the top so it seems to work partially? Tried clearing cache, cleaning up database. I'm on Pixel 8 Pro.

**Comment by diogotcorreia** [comment]
@WilliamKimball0 the fix hasn't been released yet afaik
