### ISSUE TITLE
Crash when updating Google play system

### ISSUE THREAD

**Issue by Sykomaniac** [MM2-0/Kvaesitso#23]
When Google play system attempts to update, a placeholder icon appears in the application list. Clicking the icon causes the below crash. Sorry for the formatting as I'm creating this from my phone.

![Screenshot_20220207-173934](https://user-images.githubusercontent.com/3231134/152877469-a665cb34-6a29-4592-b83a-620e30412937.png)

`Device: oriole
SDK version: 31
====================================
02-07 17:43:12.301  3651 27179 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
02-07 17:43:12.301  3651 27179 E AndroidRuntime: Process: de.mm20.launcher2.release, PID: 3651
02-07 17:43:12.301  3651 27179 E AndroidRuntime: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'de.mm20.launcher2.search.SearchableSerializer']
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:204)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem$special$$inlined$inject$default$1.invoke(KoinComponent.kt:74)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem.getSerializer(FavoritesItem.kt:21)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem.toDatabaseEntity(FavoritesItem.kt:28)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesRepositoryImpl$incrementLaunchCounter$1$1.invokeSuspend(FavoritesRepository.kt:153)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No known serializer exists for type de.mm20.launcher2.search.data.AppInstallation
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.ModuleKt$favoritesModule$1$1.invoke(Module.kt:53)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at de.mm20.launcher2.favorites.ModuleKt$favoritesModule$1$1.invoke(Module.kt:19)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
02-07 17:43:12.301  3651 27179 E AndroidRuntime: 	... 18 more`

**Comment by MM2-0** [comment]
This has already been fixed in v1.4.3. Please update to the latest version.

**Comment by Sykomaniac** [comment]
@MM2-0 it's still happening on the latest version.

https://my.owndrive.com/s/nSd4wxM3ybo99ZX

![Screenshot_20220208-093250](https://user-images.githubusercontent.com/3231134/152958787-2d6e7e9b-9500-4b51-b15b-f1be7e018299.png)

**Comment by MM2-0** [comment]
Yeah, looks like you're right.

```
02-08 09:32:01.351 18386 10728 E AndroidRuntime: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'de.mm20.launcher2.search.SearchableSerializer'. Check your definitions!
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at org.koin.core.scope.Scope.get(Scope.kt:204)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem$special$$inlined$inject$default$1.invoke(KoinComponent.kt:74)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem.getSerializer(FavoritesItem.kt:21)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesItem.toDatabaseEntity(FavoritesItem.kt:24)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at de.mm20.launcher2.favorites.FavoritesRepositoryImpl$incrementLaunchCounter$1$1.invokeSuspend(FavoritesRepository.kt:152)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02-08 09:32:01.351 18386 10728 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
