### ISSUE TITLE
Launcher widgets scroll up a little under navigation bar when using gestures

### ISSUE THREAD

**Issue by martkopecky** [MM2-0/Kvaesitso#338]
When switching apps using gestures, in some cases the closed launcher widgets scroll up a little under the navigation bar and make it no longer transparent. 

Almost like if the navigation gestures have some effect on the state of the launcher scrolling.
If you have favorites pinned as the first widget, you might even see parts of the icons in the first favorite row.

Pixel 7, default ROM, default Kvaesitso settings, version 1.23.1.

Screengrab attached.

![Navbar_scroll_issue](https://user-images.githubusercontent.com/33658071/231972687-c1a3e6e2-ec4f-4d0d-91a4-e3042d807a27.gif)

**Comment by martkopecky** [comment]
Sure, might be, I am just unable to express myself concisely. The message is: there is some scrolling happening behind the scenes when using navigation gestures and it is annoying.

In my eyes, it is clearly a bug, as even the search field appears (if it is set to be hidden) and parts of the pinned icons also, if they are present as the first widget.

**Comment by exstntlmsnthrp** [comment]
Understood. Just another user trying to help. I'm not a developer, so I don't fully understand the technical side of it or what could be causing it.

**Comment by humzasadiq** [comment]
Android 10+ doesn't let any 3rd party launcher use the gesture navigation fully. There is a fix for rooted phones. Quickswitch fixes this. But the launcher need to support it or something. Currently only support Lawnchair3 launcher.
Or the other way around is to just use the 3 button navigation bar🤧

**Comment by exstntlmsnthrp** [comment]
Whilst you are correct, the OP noted they have a Pixel 7 which comes with Android 13.  Many of the gesture problems have been resolved since version 10.

**Comment by Lootyy** [comment]
Unfortunately I'm getting the same, on Android 14. Removing all widgets and the edit button still doesn't resolve it, as the page is scrollable even without any content for some reason.

**Comment by alexandrius** [comment]
Same issue 😞

**Comment by alexandrius** [comment]
This seems to be the same issue

https://github.com/MM2-0/Kvaesitso/issues/732

@MM2-0 fixing this issue will be as easy as adding tiny dead zone on the bottom of the screen so that Kvaesitso doesn't register TOUCH_DOWN or ignores it
